name: Mirror to GitLab

on:
  push:
    branches:
      - main   # change to master if needed

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/pixelated-labs/PixelMDL.git
          git push gitlab --all
          git push gitlab --tags
